/**
 * Database Types
 * 
 * This file is auto-generated by Supabase CLI.
 * To update types, run: npm run db:types
 * 
 * For now, using minimal types for development.
 * Full types will be generated after running Supabase locally.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      consultants: {
        Row: {
          id: string
          email: string
          name: string
          bio: string | null
          whatsapp_number: string
          vertical: string
          slug: string
          business_name: string | null
          business_category: string | null
          cpf_cnpj: string | null
          website: string | null
          instagram: string | null
          logo_url: string | null
          address_street: string | null
          address_city: string | null
          address_state: string | null
          address_zip_code: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          name: string
          bio?: string | null
          whatsapp_number: string
          vertical: string
          slug: string
          business_name?: string | null
          business_category?: string | null
          cpf_cnpj?: string | null
          website?: string | null
          instagram?: string | null
          logo_url?: string | null
          address_street?: string | null
          address_city?: string | null
          address_state?: string | null
          address_zip_code?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string
          bio?: string | null
          whatsapp_number?: string
          vertical?: string
          slug?: string
          business_name?: string | null
          business_category?: string | null
          cpf_cnpj?: string | null
          website?: string | null
          instagram?: string | null
          logo_url?: string | null
          address_street?: string | null
          address_city?: string | null
          address_state?: string | null
          address_zip_code?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      whatsapp_integrations: {
        Row: {
          id: string
          consultant_id: string
          provider: string
          access_token: string | null
          waba_id: string | null
          phone_number_id: string | null
          business_account_id: string | null
          phone_number: string
          business_name: string | null
          display_name: string | null
          quality_rating: string | null
          status: string
          verified_at: string | null
          messaging_limit_tier: string | null
          last_rate_limit_check: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          consultant_id: string
          provider?: string
          access_token?: string | null
          waba_id?: string | null
          phone_number_id?: string | null
          business_account_id?: string | null
          phone_number: string
          business_name?: string | null
          display_name?: string | null
          quality_rating?: string | null
          status?: string
          verified_at?: string | null
          messaging_limit_tier?: string | null
          last_rate_limit_check?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          consultant_id?: string
          provider?: string
          access_token?: string | null
          waba_id?: string | null
          phone_number_id?: string | null
          business_account_id?: string | null
          phone_number?: string
          business_name?: string | null
          display_name?: string | null
          quality_rating?: string | null
          status?: string
          verified_at?: string | null
          messaging_limit_tier?: string | null
          last_rate_limit_check?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      messages: {
        Row: {
          id: string
          conversation_id: string | null
          consultant_id: string | null
          lead_phone: string | null
          sender: string
          content: string
          message_type: string
          direction: string | null
          platform_message_id: string | null
          status: string | null
          metadata: Json
          sent_at: string
        }
        Insert: {
          id?: string
          conversation_id?: string | null
          consultant_id?: string | null
          lead_phone?: string | null
          sender: string
          content: string
          message_type?: string
          direction?: string | null
          platform_message_id?: string | null
          status?: string | null
          metadata?: Json
          sent_at?: string
        }
        Update: {
          id?: string
          conversation_id?: string | null
          consultant_id?: string | null
          lead_phone?: string | null
          sender?: string
          content?: string
          message_type?: string
          direction?: string | null
          platform_message_id?: string | null
          status?: string | null
          metadata?: Json
          sent_at?: string
        }
      }
      // Add other tables as needed
      [key: string]: any
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
