/**
 * Database Types
 *
 * This file will be auto-generated by running:
 * npm run db:types
 *
 * Which executes: supabase gen types typescript --local > src/types/database.ts
 *
 * After creating your Supabase tables and running migrations,
 * regenerate these types to get accurate TypeScript definitions.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      consultants: {
        Row: {
          id: string;
          email: string;
          name: string;
          bio: string | null;
          whatsapp_number: string;
          vertical: string;
          slug: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          name: string;
          bio?: string | null;
          whatsapp_number: string;
          vertical: string;
          slug: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string;
          bio?: string | null;
          whatsapp_number?: string;
          vertical?: string;
          slug?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      leads: {
        Row: {
          id: string;
          consultant_id: string;
          whatsapp_number: string;
          name: string;
          email: string | null;
          status: 'novo' | 'em_contato' | 'qualificado' | 'agendado' | 'fechado' | 'perdido';
          score: number | null;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          consultant_id: string;
          whatsapp_number: string;
          name?: string;
          email?: string | null;
          status?: 'novo' | 'em_contato' | 'qualificado' | 'agendado' | 'fechado' | 'perdido';
          score?: number | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          consultant_id?: string;
          whatsapp_number?: string;
          name?: string;
          email?: string | null;
          status?: 'novo' | 'em_contato' | 'qualificado' | 'agendado' | 'fechado' | 'perdido';
          score?: number | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      // Add other tables as needed
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
