#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "👉 Running lint check"
npm run lint

# Note: type-check temporarily disabled due to test file type errors
# TODO: Fix test file types and re-enable: npm run type-check
